import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import { QueryProvider } from "@/shared/providers/QueryProvider";

const inter = Inter({
    subsets: ['cyrillic', 'latin'],
    variable: '--font-inter',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    display: 'swap'
})

const nunito = Nunito({
    subsets: ['cyrillic', 'latin'],
    variable: '--font-nunito',
    weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
    display: 'swap'
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" className={`${nunito.variable} ${inter.variable}`}>
            <body>
                <QueryProvider>
                    <MantineProvider>
                        {children}
                    </MantineProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
